### ISSUE TITLE
Can't build a project

### ISSUE THREAD

**Issue by avently** [cbeust/kobalt-android#14]
I'm getting this error when trying to build:
``
ERROR com.beust.kobalt.HostConfig.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
``

What i did:
- downloaded kobalt files from this repository (kobaltw and /kobalt/*)
- placed it into the AppName/app/ directory
- ran ./kobaltw --plugins com.beust:kobalt-android: --init androidJava
- setup Build.kt file like i did it for Gradle
- ran ./kobaltw --tasks
- got the error

What's next? How to fix it?

**Comment by cbeust** [comment]
I haven't worked on the Android plug-in in a while and it definitely needs to be updated to the latest version. Sorry, I don't have an immediate fix for you right now...

**Comment by avently** [comment]
@cbeust so what are my options now? To wait or to downgrade kobalt?

**Comment by cbeust** [comment]
Kobalt is not suited to building Android right now, sadly (it used to be, and I'm sure it still can today but it's a full time job to maintain this plug-in and I'm afraid I don't have the bandwidth right now :().
